### ISSUE TITLE
2段目への香の不成

### ISSUE THREAD

**Issue by yaneurao** [TadaoYamaoka/DeepLearningShogi#32]
> sfen 2l4nl/7p1/3ppps1p/6pP1/9/3K1PP2/1G1PPRN1P/4rg3/k1P3+b1L w Nb2g3snl5p 0
> 7a7h : 71の香を78に不成で移動させる指し手

上の局面、dlshogiは2段目(後手番なので8段目)へ香を不成で移動させる指し手を生成しています。

歩の不成と同様に、この指し手は打ち歩詰めの時しか有効になることはなく、これは生成しないほうがわずかですが強くなります。Aperyの指し手生成ルーチンが生成してしまっているのかも知れませんが…。

**Comment by TadaoYamaoka** [comment]
Aperyは歩、角、飛についてもALLでない場合も不成を生成していたので、歩、角、飛については変更していたのですが、香の2段目については修正が漏れていました。ありがとうございます！
