### ISSUE TITLE
ノード数を固定して対局させるためにNodesLimitがほしい

### ISSUE THREAD

**Issue by yaneurao** [TadaoYamaoka/DeepLearningShogi#33]
dlshogi、ノード制限しようと思ったら、UCT_NodeLimitはノード制限ではなく、単にこれを越すとメモリがなくなるので、終了するだけで、秒読み等が優先されてるように見えました。

>         if (!pondering && po_info.halt == 0 && begin_time.elapsed() > time_limit) {
となっていて、ここにはuct_node_limitは絡んでいないので、uct_node_limitの値に依らず、時間経過で思考が終了します。

dlshogi、"go nodes X "のようにgoコマンドの拡張でnodesを指定すればノード制限できるのですが、これはUSIの非標準の(?)拡張なので、これに対応しているGUIはほぼないです。

// ShogiGUIの検討モードはこれで思考させることが出来るので、ShogiGUIは対応していると言えば対応している？
// 将棋所はノード数を指定できないです。

たぬころや、私の対局スクリプトも対応していないです。なので、実質、これを指定しての対局は一般的には難しいです。

そんなわけでして、NodesLimitみたいなエンジンオプションがほしい所です。

// ふかうら王には、UCT_NodeLimitとは別にNodesLimitというエンジンオプションが用意してあります。

**Comment by TadaoYamaoka** [comment]
Const_PlayoutがNodesLimitと同じ意味のオプションになっています。
