### ISSUE TITLE
go infinite～stopに対してbestmoveが二回返ってくる

### ISSUE THREAD

**Issue by yaneurao** [TadaoYamaoka/DeepLearningShogi#34]
標題の件

例)
> isready
> go infinite
> stop
> < bestmove 2g2f
> < bestmove resign

USIプロトコルの仕様では、陽には書かれていませんが、二回bestmoveを返すと次のようなケースで誤って処理されます。

go infinite
stop
< bestmove 2g2f
// === ここでGUI側はbestmoveを受け取ったので次のposition～goコマンドを送信する ===
position XXX
go XXX
< bestmove resign
// このとき、この2度目のbestmove resignを直前のgoコマンドに対する応答であるとGUI側は解釈します。
// ゆえにここで投了したことになってしまいます。😥

**Comment by TadaoYamaoka** [comment]
ありがとうございます。ご指摘の通りです。
USIプロトコルの仕様を確認したところ、通常思考の場合もstopが送られる場合があるようなので、ponder中のみbestmove resignを返すようにしました。
