### ISSUE TITLE
テストデータは重複しない方がいい

### ISSUE THREAD

**Issue by bleu48** [TadaoYamaoka/DeepLearningShogi#41]
https://github.com/TadaoYamaoka/DeepLearningShogi/blob/c76182006c152b93b5dcb2d96558f0ed9668c000/dlshogi/train_rl_policy_with_value_using_hcpe_bootstrap.py#L146

テストデータは重複サンプルしない方が良いでしょう。
numpy.random.choiceはデフォルト重複許可ですのでreplace=Falseと加えて不許可にした方が良いように思います。
個人的には少量のテスト局面固定で毎回全データ使ってます。

**Comment by TadaoYamaoka** [comment]
ご指摘の通り重複しない方が適切でした。ありがとうございます。
