### ISSUE TITLE
自己対局棋譜を用いるとPolicyのlossがNaNになる

### ISSUE THREAD

**Issue by yaneurao** [TadaoYamaoka/DeepLearningShogi#44]
hcpe3形式で教師ファイルを生成して、それをhcpeに変換して使っています。その時に、かなり高い確率でPolicyのlossがNaNになるので原因を調査してみました。

hcpe3_to_hcpe.pyにassertを追加しました。
>           if  not(board.is_pseudo_legal(move) and board.is_legal(move)):
>             print(f"sfen = {board.sfen()} , USI = {move_to_usi(move)}")

そうすると次の局面で引っかかりました。

> sfen = 2+P6/3p1s3/4p3n/p3lpp2/7nS/PPpB4P/KS1P5/5k3/L2G5 w 2G2L5P2rbgs2n2p 1 , USI = 5d5g

57香不成です。合法手ですが、この指し手に対してcshogiのis_pseudo_legal()がFalseを返しています。

そもそもで言うと、cshogiを使う側は、pseudo_legal()とlegal()の２つを呼び出したくないので、is_legal()が↓こう実装されていて欲しい気はします。

> def is_legal(self, int move):
>	return self.__board.moveIsPseudoLegal(move) and self.__board.moveIsLegal(move)

それで、学習時にpolicyの確率を計算するときにlegal movesとして不成の指し手を生成していないのではないかと思うのです。(ソースコードを追いかけていないので、予想です。)　だとしたら、存在しない指し手を指していることになり、policyの値が壊れる気がします。上の修正をした上で、学習部で、教師棋譜の指し手がlegal movesであるかのチェックをして欲しいところです…。

**Comment by yaneurao** [comment]
ついでに書くと自己対局の時に不成の指し手を生成していないのに、evasion(王手回避)の時にだけ57香不成を生成するのは、evasionの指し手生成上のバグだと言えると思うので、これは(おそらくAperyのコードを)修正したほうがよろしいです。

**Comment by windfall-shogi** [comment]
不成が生成されないバグがあるので、57香不成がpseudo_legalから抜けているのだと思います。
#45

**Comment by yaneurao** [comment]
重複局面を削除することでlossがNaNにならなくなりました！ありがとうございます！

関連 : https://tadaoyamaoka.hatenablog.com/entry/2021/04/17/182108
