### ISSUE TITLE
検討時のMutiPV変更に追従しない

### ISSUE THREAD

**Issue by bleu48** [TadaoYamaoka/DeepLearningShogi#61]
検討エンジンとして使われるようになってきたので気になりました。
ShogiGUIで検討時にもMultiPVが変更できるのですがこれに表示側が追従しません。
起動しなおせばいいのですが副作用のない微修正なのでIssueとして挙げておきます。

**Comment by TadaoYamaoka** [comment]
ご指摘ありがとうございます。対応しました。
