### ISSUE TITLE
検討時のMateで読み筋が出ない

### ISSUE THREAD

**Issue by bleu48** [TadaoYamaoka/DeepLearningShogi#62]
検討エンジンとして使われるようになってきたので挙げておきます。
Mateを読み切った際に指し手は出るのですが何手詰めであるか，読み筋などが出ません。
多くの人に有用で副作用の少ない変更と思いますのでIssueとします。

**Comment by TadaoYamaoka** [comment]
mateの読み筋表示に対応しました。
1つでも詰みの手順が見つかった時点で探索を打ち切るため、最短手順を返すとは限りません。
