### ISSUE TITLE
dlshogi学習済みモデルのHomebrewでのFormula化に関して

### ISSUE THREAD

**Issue by Hikoyu** [TadaoYamaoka/DeepLearningShogi#63]
Macユーザー向けに将棋AIをHomebrewでインストールするリポジトリを作っています。
「ふかうら王」をONNXRUNTIMEのCPU動作版としてコンパイルして、「dlshogi」の第2回電竜戦エキシビションマッチの学習済みモデルを使えるようにFormulaを作成したのですが、インストール実行時にモデルファイル解凍のためのパスワードをユーザー側に入力させることが現状うまくできていません。
スクリプト中にパスワードを記載しておけば問題ないのですが、単にそれを行うのは山岡様の意図に反すると思われたため、ひとまずインストール時にライセンス文がコマンドラインに表示されるようにしてみたのですが、いかが思われますか？（まだ公開はしていません）

**Comment by TadaoYamaoka** [comment]
ライセンスを確認した上でパスワードを入力する行為がないと、ライセンスが意識されなくなるため、スクリプト内など他の場所に記録することは禁止させてください。

**Comment by Hikoyu** [comment]
諸々承知しました。
探索部に関しましてはGPLv3でライセンスされておりましたので（macOSでのコンパイル手順が確立すれば）Formulaを作成し公開する可能性はございますが、学習済みモデルのダウンロード及びインストールに関しましてはFormulaのスクリプトに含めないように致します。
ご回答ありがとうございました。
