### ISSUE TITLE
stopコマンドを受け付けず、usiプロトコルに違反している

### ISSUE THREAD

**Issue by qhapaq-49** [TadaoYamaoka/DeepLearningShogi#75]
githubの最新版のdlshogiはgo infiniteなどのコマンドに対してstopを受け付けなくなっております。これはusiプロトコルに反しているようです。将棋所などを使って盤面検討をする場合、go infiniteとstopによる読み手の制御は頻繁に行われるため、修正することをお勧めいたします。

2022年4月9日のponder周りのコミットが悪さをしているようです。[その直前のコミット](https://github.com/TadaoYamaoka/DeepLearningShogi/commit/b5830044f173bad50ef7f43b82393221c5aa8f8c)
では正しくstopコマンドを受け取れることを確認しています。

こちらで原因を調査＋修正することもできるかもしれませんが、原因に心当たりがありましたらご教授いただければ幸いです

**Comment by TadaoYamaoka** [comment]
バグでしたので修正しました。ご報告ありがとうございます。
