### ISSUE TITLE
将棋所アプリで起動に失敗します

### ISSUE THREAD

**Issue by y-ich** [TadaoYamaoka/DeepLearningShogi#81]
こんにちは。

Mac版将棋所にdlshogiの登録をしたところ、登録はできたのですが、起動に失敗します。

将棋所は対局を開始するときに必ずsetoptionコマンドでUSI_Hashの値の設定をする(http://shogidokoro.starfree.jp/usi.html)ようで、現在、dlshogiがUSI_Hashオプションを未サポートのためのようです。

USIプロトコル(http://web.archive.org/web/20150525174702/http://www.glaurungchess.com/shogi/usi.html)的には、USI_Hashのサポートが必須のように読めたのでこちらにイシューをあげました。
(全く詳しくないので勘違いがありましたらすみません)

対処方法としてusi.cppのOptionsMap::init(Searcher* s)に適当に
```cpp
   (*this)["USI_Hash"]                    = USIOption(256, 0, 1024);
```
を追加したら動きました。

dlshogiにはDfPn_Hashオプションがあり、正しい修正はそれとの兼ね合いがあるかと思いました。
ご検討いただけたら幸いです。

**Comment by TadaoYamaoka** [comment]
USI_Hashがsetoptionで送られてきても、「No such option: USI_Hash」を標準出力して無視しています。

USI_Hashが原因である場合、Mac版将棋所は、「No such option: USI_Hash」が標準出力されると起動に失敗するということになりますが、プロトコル外の標準出力はWindows版将棋所では無視されるので、これが原因か特定いただけないでしょうか。

usi.cppの以下の箇所をコメントアウトしても発生するでしょうか？
```
std::cout << "No such option: " << name << std::endl;
```

**Comment by y-ich** [comment]
返信ありがとうございます。

最初の対処方法をコメントアウトして戻したところ、正常に動いてしまいました。
また、ご指摘の行(No such option:出力)をコメントアウトしても動きました。

将棋所のバージョンをメモしておくべきでした。いつ将棋所をアップデートしたか記憶が定かでないですが、アプリ側で対応されたようです。
お騒がせしました。
ありがとうございました。
